spring:
  application:
    name: polls

  datasource:
    url: jdbc:postgresql://ep-morning-math-ac0hillw-pooler.sa-east-1.aws.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_TWgMv5SJsYa0
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update #
  data:
    redis:
      url: redis://default:wrcjPmp8k8Dy6UluSwOluGTbsvHjVGrr@redis-18022.c83.us-east-1-2.ec2.cloud.redislabs.com:18022
      timeout: 2s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
